### ISSUE TITLE
apsystems-ecu.0 2023-04-29 19:51:10.488	error	Ecu.ecuStateMachine() +++ socket error

### ISSUE THREAD

**Issue by unwichtig** [npeter/ioBroker.apsystems-ecu#11]
Since today I don't get data für my APS to IObroker.
It worked for about 2 weeks without any problems.

The original Website from APS is working and shows the data.
Restart of everything din't change anything,
i also shut down the Adapter for about 2h and started again.

In the Instance Tab it shows 2 green and red on connection.

Version 0.2.9

Update :
In the middle of the night it just worked well again .

**Comment by npeter** [comment]
I think it's not an adater issue.
Send me a log as file if you have more issues.

**Comment by npeter** [comment]
not an adapter issue!
