### ISSUE TITLE
energy lists wrong

### ISSUE THREAD

**Issue by goeran03** [npeter/ioBroker.apsystems-ecu#16]
I get for instance for energy_of_month_list:
{"2023.09.02":0,"0231.32.02-3::":23.07,"0000.02.71-0::":82.27,"0904.00.00":9.33,"2023.09.05":0,"0391.02.02-3::":23.1,"0000.03.10-3::":82.27,"0907.00.00":9.19,"2023.09.08":0,"0386.20.23":23.13,"0000.03.71-1::":82.27,"0910.00.00":8.82,"2023.09.11":0,"0362.20.23":23.22,"0000.03.29":82.27,"0913.00.00":3.84,"2023.09.14":0,"0211.12.02-3::":23.25,"0000.03.19":82.27,"0916.00.00":8.49,"2023.09.17":0,"0215.15.20-23::":23.28,"0000.01.10-14::":82.27,"0919.00.00":6.13,"2023.09.20":0,"0271.42.02-3::":23.37,"0000.03.36":82.27,"0922.00.00":1.03,"2023.09.23":0,"0113.12.20-23::":23.4,"0000.02.91":82.27,"0925.00.00":8.12,"2023.09.26":0,"0213.12.02-3::":23.43,"0000.02.15-8::":82.27,"0928.00.00":7.38,"2023.09.29":0,"0015.13.20-23::":23.52,"0000.02.21-2::":82.27,"1001.00.00":4.38}

I do not see how to interprete.

G.

**Comment by npeter** [comment]
Log file needed to analyze!

**Comment by goeran03** [comment]
[iobroker.2023-10-05.log.txt](https://github.com/npeter/ioBroker.apsystems-ecu/files/12820802/iobroker.2023-10-05.log.txt)
attached the logfile
thanks

**Comment by goeran03** [comment]
once again. I think this one is more meaningful
look at **2023-10-01 21:11:02.338** here was a restart

[iobroker.2023-10-01.log.gz.txt](https://github.com/npeter/ioBroker.apsystems-ecu/files/12820882/iobroker.2023-10-01.log.gz.txt)

**Comment by npeter** [comment]
1) The ECU response protocol for GetEnergyOfWeekMonthYear-services has changed.
- **energy_of_week_list**, **energy_of_month_list** and **energy_of_year_list** are affected
- can you confirm wrong values?
- protocol details: 
  - CommandGroup 12 (expected 11)
  - Power of day: 4 byte HEX (expected 2 byte HEX)

2) The ECU response protocol for GetPowerOfDay-service has changed also
- can you confirm wrong **power_ofday_list** values?
- protocol details:
  - not clear, strange

**Comment by npeter** [comment]
ECU respons format has changed!
CommandGroup 12 for energy_of_week_list, energy_of_month_list and energy_of_year_list services implemented.
power_of_day_list not reproducable. Open new issue if needed.

Solved V0.2.10
