### ISSUE TITLE
Optionen hinzufügen.

### ISSUE THREAD

**Issue by Menne01** [npeter/ioBroker.apsystems-ecu#17]
Hallo @peter_n, da du schon ewig nicht im Forum warst
mach ich das auf diesem Wege.

Mein Beitrag im Forum:

[ESP8266](https://forum.iobroker.net/user/esp8266)
ESP8266
[2. März 2024, 11:18](https://forum.iobroker.net/post/1135364)

[@peter_n](https://forum.iobroker.net/uid/16480), kannst du die Optionen im Adapter mit aufnehmen? Dann wäre das ewige Volllaufen vorbei. Das Problem dabei ist, der Adapter dann kein Connect zur ECU hat und das Log läuft und läuft...
Es muss jedes mal der Stecker gezogen werden vom Netzteil.

https://github.com/ksheumaker/homeassistant-apsystems_ecur

Grüße

**Comment by npeter** [comment]
see ..
[ [Test Adapter apsystems\-ecu v0\.2\.x GitHub](/post/1136269):](https://forum.iobroker.net/topic/49362/test-adapter-apsystems-ecu-v0-2-x-github/160)

**Comment by Menne01** [comment]
Ich habe das elegant anders gelöst und das funktioniert bis jetzt. Einfach die Antenne ein Meter abgesetzt. Wie im Homeassist link von mir  beschrieben.
Hast du eventuell von der ECU das TCP User/Passswort ?
