### ISSUE TITLE
Peak Power of the Day

### ISSUE THREAD

**Issue by bu-na** [npeter/ioBroker.apsystems-ecu#4]
To simplify the  visualization (VIS) please provide a continuously updated single value who records the peak power of the current day. At midnight, this value should be set back to zero. Even a additional value for yesterday would be good.

**Comment by npeter** [comment]
@bu-na what do you think about:
- ecu.dc_power: sum of dc_power of all inverters - current value
- ecu.max_dc_power: max of ecu.dc_power - cleared at midnight
- ecu.max_dc_power_yesterday: ecu.max_dc_power saved at midnight

**Comment by bu-na** [comment]
Sounds good, I'm not sure, how ecu calcutates last_system_power, probabely there is there no difference between this value and ecu.dc_power)
how about:

ecu.last_system_power = current power value 
ecu.peak_power_today= Maximum of ecu.last_system_power (drag indicator)
ecu.peak_power_yesterday= ecu.peak_power_today at midnight

**Comment by npeter** [comment]
Function added V0.2.4
