### ISSUE TITLE
Request: Total_Energy_Yesterday

### ISSUE THREAD

**Issue by npeter** [npeter/ioBroker.apsystems-ecu#5]
Hätte mit Blick auf die Visualisierung noch folgende Vorschläge:
#1 current_day_energy=0 um Mitternacht
#2 Bereitstellen singlevalue Total_Energy_Yesterday

Solution:
  ecu.total_energy_yesterday - ecu.current_day_energy saved at midnight
  clear ecu.current_energy tbc

Remark: 
- ecu.current_day_energy ist not set to 0 by ECU-R at midnight
- to clear ecu.current_day_energy saved once will not help
- investigation ongoing

**Comment by bu-na** [comment]
Maybe it is easier to create new datapoints and calculate it specifically from midnigth (e.g. ecu.total_energy_today, ecu.total_energy_yesterday). It also may make sense for ecu.last_system_power --> ecu.current_system_power (zero at midnight problem).
We also should bear in mind that the inverters also generate energy even after sunset (even at full moon in summer) and be included in the calculations of the ECU.

**Comment by npeter** [comment]
@bu-na 
> We also should bear in mind that the inverters also generate energy even after sunset (even at full moon in summer) and be included in the calculations of the ECU.

Configuration: 
New parameter poll_always added. poll_always = true will disable stop of polling at sunsset.

**Comment by npeter** [comment]
Function added V0.2.4

**Comment by npeter** [comment]
Function added V0.2.4

**Comment by npeter** [comment]
Function added V0.2.4
