### ISSUE TITLE
How to get startet?

### ISSUE THREAD

**Issue by cyber-age** [npeter/ioBroker.apsystems-ecu#6]
Hi,
how do I get this plugin running? 
Were could I configure ist in ioBroker? Installing was possible but I can't find any configuration options...

**Comment by npeter** [comment]
You have to create a instance manualy after installation (this is always needed for installations from github).
Command line: 
`iobroker add apsystems-ecu`
Don't forget to configure your ECU WLAN IP 

See: https://forum.iobroker.net/topic/49362/test-adapter-apsystems-ecu-v0-2-x-github

**Comment by cyber-age** [comment]
Danke/Thank you
