### ISSUE TITLE
DS3 Support

### ISSUE THREAD

**Issue by cyber-age** [npeter/ioBroker.apsystems-ecu#7]
Hello,
like suggested [here](https://forum.iobroker.net/topic/49362/test-adapter-apsystems-ecu-v0-2-x-github/31?_=1647255564075)  I'm opening an Issue for DS3 Support.
Attached an Logfile after clear restart the Plugin an a Screenshot of the added states.
If more informations are needed please let me know ...

[log_apsystems_iobroker.txt](https://github.com/npeter/ioBroker.apsystems-ecu/files/8244190/log_apsystems_iobroker.txt)
![CleanShot 2022-03-14 at 12 11 09](https://user-images.githubusercontent.com/32206514/158160976-9fb51e31-5a77-414a-91ff-016fb6676375.png)

**Comment by npeter** [comment]
Full DS3 support finaly added with version V 0.2.8.
