### ISSUE TITLE
Adapter don't work probably with ECU-R. On ECU-B without issue.

### ISSUE THREAD

**Issue by stundenblume** [npeter/ioBroker.apsystems-ecu#8]
1. Thank you very much for this very useful adapter!

I have two ECU devices one ECU-B and one ECU-R.
The ECU-B device works really great. With the ECU-R the adapter only get information from the ECU-R itself but not the connected inverters.
The inverters are recognized.

The ECU-R instance "connected to device" indicator gets red after a few second. I also have to restart the adapter every five minutes to poll data from the ECU-R.

For test purpose I installed Home Assistant, there everything work normal.

ECU-R: ECU_R_PRO_2.0.5p
ECU-B: ECU_B_1.2.20

ioBoker: 5.2.3 on docker
Adapter: 0.2.3
NodeJS: 14.19
NPM: 6.14.16
installed via Git URL

Error massage: Ecu.ecuStateMachine() +++ socket error
Warning: Ecu.ecuStateMachine() - no response from Ecu, repeat service ...
Warning: rspWatchDog +++ timeout

**Comment by npeter** [comment]
I’ll check beginning of next week!

**Comment by stundenblume** [comment]
OK fine :)
I just found this [thread](https://forum.iobroker.net/topic/49362/test-adapter-apsystems-ecu-v0-2-x-github/27?_=1647634855210). After reading it I think I should mansion that I run two DS3-S (recognized as YC600) and four QS1 on the ECU-R and just one QS1 on the ECU-B.

**Comment by npeter** [comment]
DS3 inverters now detected and fully supported .
ECU-B is working as reported by some users. 
Not clear what are the required boundary conditions FW-Version, communication state (LAN, WLAN, Cloud connection).
